# Site settings
name: Nathan Homka
title: Nathan Homka
email: nathan.homka@gmail.com
author: Nathan Homka
baseurl: ""
permalink: :title
permalink: /blog/:year/:month/:day/:title

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
